### ISSUE TITLE
Curseforge Upload

### ISSUE THREAD

**Issue by TheBlueCrystal** [cam72cam/ImmersiveRailroading#203]
Hello,
yesterday I stumbled over your great mod in search of a better railway / train simulation in Minecraft.
I watched your preview-videos and was really excited about the high quality, details and love with wich this mod was made. Really great work. So I downloaded the Beta-0.4.6 for MC-1.11.2 to test with normal gameplay.
But the jar file contains unobfuscated class-files. So the game crashes on load with:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ImmersiveRailroading (immersiverailroading)
Caused by: java.lang.NoSuchFieldError: IRON
        at cam72cam.immersiverailroading.blocks.BlockRailBase.<init>(BlockRailBase.java:49)
        at cam72cam.immersiverailroading.blocks.BlockRailGag.<init>(BlockRailGag.java:22)
        at cam72cam.immersiverailroading.ImmersiveRailroading.<clinit>(ImmersiveRailroading.java:43)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:552)

I don't know if that is intended (for development environment only-tests) or if that happened by mistake.
Just wanted to let you know.

Please keep up the superb work you are doing with this mod! :)

**Comment by cam72cam** [comment]
Thanks, I must have copied the file before gradle build finished.

I am updating curseforge file description and putting a link in there to this file:
https://github.com/cam72cam/ImmersiveRailroading/releases/download/beta_0.4.6/ImmersiveRailroading-0.4.6_1.11.jar

I can't update curseforge releases without re-building and re-uploading all of my files

**Comment by dcbartlett** [comment]
@cam72cam this above error is again existent in ImmersiveRailroading-0.5.1_1.10.jar on releases on github.

**Comment by cam72cam** [comment]
I posted a fixed version on the curseforge page
