### ISSUE TITLE
Sound System crash in 1.10

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#232]
java.lang.NullPointerException: Ticking entity
    at paulscode.sound.SoundSystem.play(SoundSystem.java:1170)
    at cam72cam.immersiverailroading.sound.ClientSound.play(ClientSound.java:62)
    at cam72cam.immersiverailroading.entity.LocomotiveSteam.func_70071h(LocomotiveSteam.java:240)
    at net.minecraft.world.World.func_72866_a(World.java:1967)
    at net.minecraft.world.World.func_72870_g(World.java:1937)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by cam72cam** [comment]
Possibly a conflict with DynamicSurroundings
