### ISSUE TITLE
Sound system crashes

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#238]
[crash-2018-03-07_20.21.05-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/1793066/crash-2018-03-07_20.21.05-server.txt)

**Comment by cam72cam** [comment]
```
java.lang.NullPointerException: Exception in server tick loop
	at paulscode.sound.SoundSystem.setPitch(SoundSystem.java:1009)
	at cam72cam.immersiverailroading.sound.ClientSound.setPitch(ClientSound.java:90)
	at cam72cam.immersiverailroading.proxy.ClientProxy.onEnterChunk(ClientProxy.java:536)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_121_ClientProxy_onEnterChunk_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:739)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:534)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:483)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by cam72cam** [comment]
dynamic sounds
