### ISSUE TITLE
Game launch bug

### ISSUE THREAD

**Issue by IndieMaker** [cam72cam/ImmersiveRailroading#295]
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Railroading (immersiverailroading)"

![image](https://user-images.githubusercontent.com/38408812/38783575-c77b80fe-40d1-11e8-90ca-feca0bee60f6.png)

**Comment by redgoblin88** [comment]
could you share the crashlog itself? it an be found in the root directory (or install location) of the modpack, should be a file called "crash-reports" and its the one that was generated on that day (if by any random chance it was not generated, please provide the ".log" file which is refreshed each time you lauch the game)

**Comment by IndieMaker** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 15/04/18 19:35
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Railroading (immersiverailroading)
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:1055)
	at cam72cam.immersiverailroading.util.OreHelper$OreAbstract.getOres(OreHelper.java:45)
	at cam72cam.immersiverailroading.util.OreHelper$OreAbstract.example(OreHelper.java:67)
	at cam72cam.immersiverailroading.multiblock.MultiblockComponent.<init>(MultiblockComponent.java:33)
	at cam72cam.immersiverailroading.multiblock.Multiblock.L_ENG(Multiblock.java:44)
	at cam72cam.immersiverailroading.multiblock.SteamHammerMultiblock.<init>(SteamHammerMultiblock.java:30)
	at cam72cam.immersiverailroading.proxy.CommonProxy.init(CommonProxy.java:135)
	at cam72cam.immersiverailroading.proxy.ClientProxy.init(ClientProxy.java:209)
	at cam72cam.immersiverailroading.ImmersiveRailroading.init(ImmersiveRailroading.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 263882840 bytes (251 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E7 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCHI	chisel{MC1.10.2-0.2.0.42} [Chisel] (Chisel-MC1.10.2-0.2.0.42.jar) 
	UCHI	trackapi{1.1} [Track API] (TrackAPI-1.1_1.10.jar) 
	UCHE	immersiverailroading{1.0.1} [Immersive Railroading] (ImmersiveRailroading-1.0.1_1.10.jar) 
	UCHI	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 620'
	OptiFine Version: OptiFine_1.10.2_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by cam72cam** [comment]
Give http://174.138.127.16/job/Immersive%20Railroading/177/artifact/build/libs/ImmersiveRailroading-1.0.1_1.12-177.jar a try

**Comment by cam72cam** [comment]
Scratch that, http://174.138.127.16/job/Immersive%20Railroading%201.10.2/20/
