### ISSUE TITLE
Fix infinite loop in recursive move

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#39]
Reported by @MrBurd

```
[17:58:33] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
(...)
Caused by: java.lang.StackOverflowError
    at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.railFromPosition(EntityMoveableRollingStock.java:364) ~[EntityMoveableRollingStock.class:?]
    at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.nextPosition(EntityMoveableRollingStock.java:390) ~[EntityMoveableRollingStock.class:?]
    at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.moveRollingStock(EntityMoveableRollingStock.java:298) ~[EntityMoveableRollingStock.class:?]
    at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.recursiveMove(EntityCoupleableRollingStock.java:265) ~[EntityCoupleableRollingStock.class:?]
there's a summary
```

**Comment by MrBurd** [comment]
hey, credit me

**Comment by cam72cam** [comment]
Sorry about that, did not know you had a github account

**Comment by cam72cam** [comment]
Netcode rewrite fixed it
