### ISSUE TITLE
Decouple on server stop

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#41]
```
java.lang.Exception: DECOUPLE
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.func_70106_y(EntityCoupleableRollingStock.java:167) [EntityCoupleableRollingStock.class:?]
	at cam72cam.immersiverailroading.entity.Freight.func_70106_y(Freight.java:95) [Freight.class:?]
	at cam72cam.immersiverailroading.entity.Locomotive.func_70106_y(Locomotive.java:85) [Locomotive.class:?]
	at net.minecraft.world.World.func_72973_f(World.java:1255) [amu.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:400) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:841) [pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:452) [gw.class:?]
	at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:283) [pa$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1381) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1393) [MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:279) [pa.class:?]
	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1070) [pl.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:431) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1567) [MinecraftServer$4.class:?]

```

**Comment by cam72cam** [comment]
This did not break anything but it is still weird

**Comment by cam72cam** [comment]
This came from setDead called when a player disconnects when riding an entity.

WTF minecraft.

I added a hack a week or two ago to fix this.
