### ISSUE TITLE
getSpeedRetarderSlowdown crash

### ISSUE THREAD

**Issue by Astewen** [cam72cam/ImmersiveRailroading#557]
I hope something can be done to fix this... I have a world I've invested a LOT of time building rails and diesel production. I would really hate to lose this world, I had gone farther in it than any other to-date. I only had one boxcar and one diesel engine built, I had not made any speed retarders referred to in the crash report. I exited the world to reboot (a lag problem) and when I tried to re-open the world I got a crash report right after "loading terrain"...

ImmersiveRailroading-1.5.0_1.12-402.jar
TrackAPI-1.1_1.12.jar

`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk$EnumCreateEntityType
	at cam72cam.immersiverailroading.entity.EntityMoveableRollingStock.getSpeedRetarderSlowdown(EntityMoveableRollingStock.java:564)
	at cam72cam.immersiverailroading.physics.PhysicsAccummulator.accumulate(PhysicsAccummulator.java:59)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.getMovement(EntityCoupleableRollingStock.java:347)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.simulateCoupledRollingStock(EntityCoupleableRollingStock.java:372)
	at cam72cam.immersiverailroading.entity.EntityCoupleableRollingStock.tickPosRemainingCheck(EntityCoupleableRollingStock.java:328)
	at cam72cam.immersiverailroading.proxy.CommonProxy.onWorldTick(CommonProxy.java:241)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_569_CommonProxy_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk$EnumCreateEntityType
`

**Comment by CelestiaTheDryad** [comment]
That's not an error that would be caused by anything specific in your world (unless something really funky is going on). Can you gives us the forge version and upload the full log to dropbox or pastebin please?

**Comment by Astewen** [comment]
Thanks for the reply CelestiaTheDryad, but  I think i'll just close this... I seem to only have the backup now and it's giving a different error (not IR related). If it pops back up I'll start a new issue. Thanks again.
