### ISSUE TITLE
Server crash NPE- TileRailBase.writeToNBT

### ISSUE THREAD

**Issue by ProsperCraft** [cam72cam/ImmersiveRailroading#570]
https://gist.github.com/ProsperCraft/ecf9efd1f34435e81d2e04635b9ea72e

java.lang.NullPointerException
    at cam72cam.immersiverailroading.tile.TileRailBase.writeToNBT(TileRailBase.java:290)
    at cam72cam.immersiverailroading.tile.SyncdTileEntity.getUpdateTag(SyncdTileEntity.java:71)

**Comment by hayesj1** [comment]
What were you doing just before the crash occurred? That's a very strange crash.

**Comment by cam72cam** [comment]
Did someone try to auto place track using a ex-u placer or similar?

**Comment by ProsperCraft** [comment]
Trying to get answers from the town owner.

**Comment by ProsperCraft** [comment]
1:00 AM] Geigren (Esiglos): I was not, I have a small rail system going around my town, auto filling my engine with water and charcoal blocks, auto filling + emptying a tank car of crude oil, and a cargo car of charcoal blocks
[1:03 AM] Geigren (Esiglos): This system has been up and running for several months now, i recently however re-arranged some of the fluid/item loader/unloaders

**Comment by cam72cam** [comment]
I think I've fixed this, let me know if the problem persists
