### ISSUE TITLE
Game Crash when "building terrain" 

### ISSUE THREAD

**Issue by RankedEffects** [cam72cam/ImmersiveRailroading#574]
So, recently, i've been running into an issue while loading up worlds using the Immersive Railroading mod.

Here is my crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 4/10/19 10:34 PM
Description: Exception in server tick loop

java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.newNode(HashMap.java:1734)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:60)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88)
	at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:31)
	at net.minecraft.world.storage.MapStorage.func_75742_a(SourceFile:49)
	at com.clussmanproductions.trafficcontrol.statewatcher.StateWatcherData.get(StateWatcherData.java:108)
	at com.clussmanproductions.trafficcontrol.statewatcher.StateWatcher.addStateWatcher(StateWatcher.java:90)
	at com.clussmanproductions.trafficcontrol.tileentity.StreetLightSingleTileEntity.addStateWatchers(StreetLightSingleTileEntity.java:207)
	at com.clussmanproductions.trafficcontrol.tileentity.StreetLightSingleTileEntity.onLoad(StreetLightSingleTileEntity.java:51)
	at net.minecraft.world.World.func_175700_a(World.java:1921)
	at net.minecraft.world.World.func_147448_a(World.java:1948)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:186)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1355521584 bytes (1292 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version         | Source                                            | Signature                                |
	|:------- |:-------------------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft            | 1.12.2          | minecraft.jar                                     | None                                     |
	| UCHIJAA | mcp                  | 9.42            | minecraft.jar                                     | None                                     |
	| UCHIJAA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | cfm                  | 6.2.0           | cfm-6.2.0-mc1.12.2.jar                            | None                                     |
	| UCHIJAA | codechickenlib       | 3.2.2.353       | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | trackapi             | 1.1             | TrackAPI-1.1_1.12.jar                             | None                                     |
	| UCHIJAA | jei                  | 4.14.4.264      | jei_1.12.2-4.14.4.264.jar                         | None                                     |
	| UCHIJAA | immersiveengineering | 0.12-89         | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAA | immersiverailroading | 1.5.0           | ImmersiveRailroading-1.5.0_1.12-402.jar           | None                                     |
	| UCHIJAA | malisiscore          | 1.12.2-6.4.0    | MalisisCore-1.12.2.jar                            | None                                     |
	| UCHIJAA | malisisdoors         | 1.12.2-7.3.0    | MalisisDoors-Mod-1.12.2.jar                       | None                                     |
	| UCHIJAA | modroadworksreborn   | 0.0.3           | modroadworksreborn-0.0.3.jar                      | None                                     |
	| UCHIJAA | nei                  | 2.4.2           | NotEnoughItems-1.12.2-2.4.2.240-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | trafficcontrol       | 0.0.2           | trafficcontrol-0.0.3.jar                          | None                                     |
	| UCHIJAA | worldedit            | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 17
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

If you want my PC Specs, please comment below, I would love to figure out this issue because i've been building this world up for days, Thank you.

**Comment by km00700** [comment]
You ran out of memory loading the world. If you have 8 or more GB of installed memory, I advise you allocate between 4-6 GB of memory to MC.

**Comment by cam72cam** [comment]
You could try adding foamfix, but if you have more memory you should take advantage of it using -Xmx4G or -Xmx6G
