### ISSUE TITLE
Crash when laying snow blocks beside track

### ISSUE THREAD

**Issue by Railroadactive** [cam72cam/ImmersiveRailroading#606]
I was placing snow blocks beside the track when I accidently right clicked the track, the screen went blue and then I got the notification that it crashed when tesslating block. I've tried to reboot the world and it crashes every time. Her is the report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/5/19 5:59 PM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} to 10 on block minecraft:snow_layer, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at cam72cam.immersiverailroading.render.block.RailBaseModel.func_188616_a(RailBaseModel.java:80)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at cam72cam.immersiverailroading.render.block.RailBaseModel.func_188616_a(RailBaseModel.java:80)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)

-- Block model being tesselated --
Details:
	Block: immersiverailroading:block_rail_gag
	Block location: World: (-3594,68,-84), Chunk: (at 6,4,12 in -225,-6; contains blocks -3600,0,-96 to -3585,255,-81), Region: (-8,-1; contains chunks -256,-32 to -225,-1, blocks -4096,0,-512 to -3585,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #298 (tile.immersiverailroading:block_rail_gag // cam72cam.immersiverailroading.blocks.BlockRailGag)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-3594,68,-84), Chunk: (at 6,4,12 in -225,-6; contains blocks -3600,0,-96 to -3585,255,-81), Region: (-8,-1; contains chunks -256,-32 to -225,-1, blocks -4096,0,-512 to -3585,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['trainmanzach'/250, l='MpServer', x=-3591.96, y=69.00, z=-83.60]]
	Chunk stats: MultiplayerChunkCache: 265, 265
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 50328566 game time, 50328566 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityItem['item.item.snowball'/323, l='MpServer', x=-3623.86, y=68.10, z=-90.69], EntityItem['item.item.snowball'/324, l='MpServer', x=-3625.85, y=68.10, z=-89.10], EntityItem['item.item.snowball'/325, l='MpServer', x=-3622.74, y=68.10, z=-89.06], EntityItem['item.item.snowball'/326, l='MpServer', x=-3621.55, y=67.00, z=-87.66], EntityItem['item.item.snowball'/327, l='MpServer', x=-3624.13, y=68.10, z=-88.31], EntityItem['item.item.snowball'/328, l='MpServer', x=-3619.40, y=67.00, z=-86.78], EntityItem['item.item.snowball'/329, l='MpServer', x=-3617.61, y=68.10, z=-87.73], EntityItem['item.item.snowball'/330, l='MpServer', x=-3620.34, y=68.10, z=-89.70], EntityItem['item.item.snowball'/331, l='MpServer', x=-3618.04, y=68.10, z=-89.65], EntityItem['item.item.snowball'/332, l='MpServer', x=-3616.57, y=68.10, z=-88.72], EntitySquid['Squid'/333, l='MpServer', x=-3644.60, y=61.00, z=-67.51], EntitySquid['Squid'/334, l='MpServer', x=-3640.58, y=61.14, z=-66.54], EntitySquid['Squid'/335, l='MpServer', x=-3640.50, y=60.13, z=-65.90], EntityBat['Bat'/336, l='MpServer', x=-3623.97, y=47.59, z=-99.84], EntityBat['Bat'/337, l='MpServer', x=-3638.24, y=42.51, z=-92.25], EntityRabbit['Rabbit'/338, l='MpServer', x=-3627.13, y=70.00, z=-124.49], EntityRabbit['Rabbit'/339, l='MpServer', x=-3624.15, y=70.00, z=-125.49], EntityMinecartChest['Minecart with Chest'/340, l='MpServer', x=-3662.50, y=17.06, z=-84.50], EntityItem['item.item.snowball'/341, l='MpServer', x=-3651.05, y=68.10, z=-92.81], EntityMinecartChest['Minecart with Chest'/342, l='MpServer', x=-3636.50, y=33.06, z=-115.50], EntityRabbit['Rabbit'/345, l='MpServer', x=-3638.83, y=67.00, z=-149.53], EntityRabbit['Rabbit'/346, l='MpServer', x=-3637.83, y=69.00, z=-131.17], EntityRabbit['Rabbit'/347, l='MpServer', x=-3639.03, y=71.00, z=-141.00], EntityMinecartChest['Minecart with Chest'/349, l='MpServer', x=-3638.50, y=32.06, z=-162.50], EntityPlayerSP['trainmanzach'/250, l='MpServer', x=-3591.96, y=69.00, z=-83.60], EntityRabbit['Rabbit'/306, l='MpServer', x=-3667.40, y=65.00, z=-140.47], MagicEntity['unknown'/-31415, l='MpServer', x=-3592.81, y=68.82, z=-83.78]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 757914456 bytes (722 MB) / 2113929216 bytes (2016 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2627 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version         | Source                                   | Signature                                |
	|:--------- |:-------------------- |:--------------- |:---------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2          | minecraft.jar                            | None                                     |
	| UCHIJAAAA | mcp                  | 9.42            | minecraft.jar                            | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.2.2627.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2627    | forge-1.12.2-14.23.2.2627.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater    | 1.0             | MercuriusUpdater-1.12.2.jar              | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.1.6.339       | CodeChickenLib-1.12.2.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | jei                  | 4.9.1.168       | jei_1.12.2-4.9.1.168.jar                 | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                 | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.9.0.55 | Tinkers-Construct-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-80         | ImmersiveEngineering-0.12-80.jar         | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | trackapi             | 1.1             | TrackAPI-1.1_1.12.jar                    | None                                     |
	| UCHIJAAAA | immersiverailroading | 1.6.1           | ImmersiveRailroading-1.6.1_1.12-1138.jar | None                                     |
	| UCHIJAAAA | nei                  | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4815' Renderer: 'Intel(R) UHD Graphics 620'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2627
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 22.20.16.4815, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: American+Freight+Pack.zip, American+Caboose+Pack+v2.0.zip, American+Steam+Locomotive+Pack (1).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz``

**Comment by Railroadactive** [comment]
Can anybody help me? Is there any way to get my world back?

**Comment by Larky2k** [comment]
Worldedit that chubk, try wintetwonderland mod

**Comment by cam72cam** [comment]
This is definitely an issue in IR.  The code that I use to move snow off of the tracks must be bugged.  I will try to post a jar either this week or next with a fix for you and put a proper fix in the next version

**Comment by cam72cam** [comment]
Here's a temporary fix to get your world working again: https://drive.google.com/open?id=1xIm4ZbV6Ud-Iw6sBdpqU3DZ-1_GVa6gK

**Comment by Railroadactive** [comment]
I tried your fix but the screen still went light blue and the game crashed

**Comment by cam72cam** [comment]
Can you post the crash with the test version?

**Comment by Railroadactive** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/19/19 5:34 PM
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} to 10 on block minecraft:snow_layer, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at cam72cam.immersiverailroading.render.block.RailBaseModel.func_188616_a(RailBaseModel.java:80)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at cam72cam.immersiverailroading.render.block.RailBaseModel.func_188616_a(RailBaseModel.java:80)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:99)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)

-- Block model being tesselated --
Details:
	Block: immersiverailroading:block_rail_gag
	Block location: World: (-3594,68,-84), Chunk: (at 6,4,12 in -225,-6; contains blocks -3600,0,-96 to -3585,255,-81), Region: (-8,-1; contains chunks -256,-32 to -225,-1, blocks -4096,0,-512 to -3585,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #298 (tile.immersiverailroading:block_rail_gag // cam72cam.immersiverailroading.blocks.BlockRailGag)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-3594,68,-84), Chunk: (at 6,4,12 in -225,-6; contains blocks -3600,0,-96 to -3585,255,-81), Region: (-8,-1; contains chunks -256,-32 to -225,-1, blocks -4096,0,-512 to -3585,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:172)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:976)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1316)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['trainmanzach'/250, l='MpServer', x=-3591.96, y=69.00, z=-83.60]]
	Chunk stats: MultiplayerChunkCache: 250, 250
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 50328821 game time, 50328821 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntitySquid['Squid'/320, l='MpServer', x=-3638.49, y=60.68, z=-67.37], EntityMinecartChest['Minecart with Chest'/322, l='MpServer', x=-3638.50, y=32.06, z=-162.50], EntityRabbit['Rabbit'/291, l='MpServer', x=-3667.40, y=65.00, z=-140.47], EntityMinecartChest['Minecart with Chest'/323, l='MpServer', x=-3636.50, y=33.06, z=-115.50], EntityRabbit['Rabbit'/324, l='MpServer', x=-3637.83, y=69.00, z=-131.17], EntityRabbit['Rabbit'/325, l='MpServer', x=-3638.79, y=71.00, z=-141.55], EntityRabbit['Rabbit'/326, l='MpServer', x=-3638.83, y=67.00, z=-149.53], EntityItem['item.item.snowball'/300, l='MpServer', x=-3557.92, y=68.79, z=-67.43], EntityItem['item.item.snowball'/301, l='MpServer', x=-3558.88, y=68.00, z=-69.92], EntityItem['item.item.snowball'/302, l='MpServer', x=-3559.17, y=68.77, z=-67.32], EntityPlayerSP['trainmanzach'/250, l='MpServer', x=-3591.96, y=69.00, z=-83.60], EntityItem['item.item.snowball'/303, l='MpServer', x=-3560.78, y=68.00, z=-66.63], EntityItem['item.item.snowball'/304, l='MpServer', x=-3559.21, y=68.77, z=-66.34], MagicEntity['unknown'/-31415, l='MpServer', x=-3592.81, y=68.82, z=-83.78], EntityBat['Bat'/314, l='MpServer', x=-3638.52, y=44.99, z=-82.47], EntityMinecartChest['Minecart with Chest'/316, l='MpServer', x=-3662.50, y=17.06, z=-84.50], EntityItem['item.item.snowball'/317, l='MpServer', x=-3651.05, y=68.10, z=-92.81], EntitySquid['Squid'/318, l='MpServer', x=-3643.70, y=61.15, z=-65.40], EntitySquid['Squid'/319, l='MpServer', x=-3641.40, y=61.20, z=-69.60]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 855395768 bytes (815 MB) / 2298478592 bytes (2192 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2627 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version         | Source                                  | Signature                                |
	|:--------- |:-------------------- |:--------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2          | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                  | 9.42            | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.2.2627.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2627    | forge-1.12.2-14.23.2.2627.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater    | 1.0             | MercuriusUpdater-1.12.2.jar             | None                                     |
	| UCHIJAAAA | codechickenlib       | 3.1.6.339       | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | jei                  | 4.9.1.168       | jei_1.12.2-4.9.1.168.jar                | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.9.0.55 | Tinkers-Construct-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-80         | ImmersiveEngineering-0.12-80.jar        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | trackapi             | 1.1             | TrackAPI-1.1_1.12.jar                   | None                                     |
	| UCHIJAAAA | immersiverailroading | 1.6.1           | ImmersiveRailroading-1.6.1_snowfix.jar  | None                                     |
	| UCHIJAAAA | nei                  | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4815' Renderer: 'Intel(R) UHD Graphics 620'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2627
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 22.20.16.4815, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: American+Freight+Pack.zip, American+Caboose+Pack+v2.0.zip, American+Steam+Locomotive+Pack (1).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by cam72cam** [comment]
Ah, I used a max function when I should have used a min function.  Will have another build in a few minutes

**Comment by cam72cam** [comment]
https://drive.google.com/open?id=1eMwHr7lWm_dewJJ0Iyrpvususd90cifu

**Comment by Railroadactive** [comment]
It worked! thank you very much!!!!!

**Comment by cam72cam** [comment]
Awesome, I'll include that fix or a similar version in the next update
