### ISSUE TITLE
Many Error Messages in console.

### ISSUE THREAD

**Issue by djdanby** [cam72cam/ImmersiveRailroading#612]
I have many errors in my server log. But i can find the "btir_locomotive_unu_at410hpr_2085"

Does anyone have an idea where these error messages could come from? I checked all resource packages available on the server. In no one is this component.

Forge Version: forge-1.12.2-14.23.5.2838-universal

```[09:44:13] [Server thread/ERROR] [immersiverailroading]: Catching
java.io.FileNotFoundException: immersiverailroading:models/rolling_stock/locomotives/btir_locomotive_unu_at410hpr_2085/btir_locomotive_unu_at410hpr_2085.obj
	at cam72cam.immersiverailroading.proxy.CommonProxy.getResourceStream(CommonProxy.java:278) ~[CommonProxy.class:?]
	at cam72cam.immersiverailroading.model.obj.OBJModel.<init>(OBJModel.java:46) ~[OBJModel.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.parseJson(EntityRollingStockDefinition.java:142) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.parseJson(FreightDefinition.java:14) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.parseJson(LocomotiveDefinition.java:36) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.parseJson(LocomotiveDieselDefinition.java:59) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.<init>(EntityRollingStockDefinition.java:106) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.<init>(FreightDefinition.java:10) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.<init>(LocomotiveDefinition.java:23) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.<init>(LocomotiveDieselDefinition.java:27) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$static$0(DefinitionManager.java:46) ~[DefinitionManager.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.initDefinitions(DefinitionManager.java:147) [DefinitionManager.class:?]
	at cam72cam.immersiverailroading.proxy.CommonProxy.preInit(CommonProxy.java:113) [CommonProxy.class:?]
	at cam72cam.immersiverailroading.proxy.ServerProxy.preInit(ServerProxy.java:41) [ServerProxy.class:?]
	at cam72cam.immersiverailroading.ImmersiveRailroading.preInit(ImmersiveRailroading.java:45) [ImmersiveRailroading.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[09:44:13] [Server thread/INFO] [immersiverailroading]: Loading stock rolling_stock/locomotives/btir_locomotive_unu_pc409hpr_2085.json
[09:44:13] [Server thread/ERROR] [immersiverailroading]: Catching
java.io.FileNotFoundException: immersiverailroading:models/rolling_stock/locomotives/btir_locomotive_unu_pc409hpr_2085/btir_locomotive_unu_pc409hpr_2085.obj
	at cam72cam.immersiverailroading.proxy.CommonProxy.getResourceStream(CommonProxy.java:278) ~[CommonProxy.class:?]
	at cam72cam.immersiverailroading.model.obj.OBJModel.<init>(OBJModel.java:46) ~[OBJModel.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.parseJson(EntityRollingStockDefinition.java:142) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.parseJson(FreightDefinition.java:14) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.parseJson(LocomotiveDefinition.java:36) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.parseJson(LocomotiveDieselDefinition.java:59) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.<init>(EntityRollingStockDefinition.java:106) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.<init>(FreightDefinition.java:10) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.<init>(LocomotiveDefinition.java:23) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.<init>(LocomotiveDieselDefinition.java:27) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$static$0(DefinitionManager.java:46) ~[DefinitionManager.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.initDefinitions(DefinitionManager.java:147) [DefinitionManager.class:?]
	at cam72cam.immersiverailroading.proxy.CommonProxy.preInit(CommonProxy.java:113) [CommonProxy.class:?]
	at cam72cam.immersiverailroading.proxy.ServerProxy.preInit(ServerProxy.java:41) [ServerProxy.class:?]
	at cam72cam.immersiverailroading.ImmersiveRailroading.preInit(ImmersiveRailroading.java:45) [ImmersiveRailroading.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[09:44:13] [Server thread/INFO] [immersiverailroading]: Loading stock rolling_stock/locomotives/btcivil_vehicle_unu_sv313mcc_2084_rail.json
[09:44:13] [Server thread/INFO] [immersiverailroading]: Loading stock rolling_stock/locomotives/btir_locomotive_unu_sc126hcr_2081_double.json
[09:44:13] [Server thread/ERROR] [immersiverailroading]: Catching
java.io.FileNotFoundException: immersiverailroading:models/rolling_stock/locomotives/btir_locomotive_unu_sc126hcr_2081_double/btir_locomotive_unu_sc126hcr_2081_double.obj
	at cam72cam.immersiverailroading.proxy.CommonProxy.getResourceStream(CommonProxy.java:278) ~[CommonProxy.class:?]
	at cam72cam.immersiverailroading.model.obj.OBJModel.<init>(OBJModel.java:46) ~[OBJModel.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.parseJson(EntityRollingStockDefinition.java:142) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.parseJson(FreightDefinition.java:14) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.parseJson(LocomotiveDefinition.java:36) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.parseJson(LocomotiveDieselDefinition.java:59) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.EntityRollingStockDefinition.<init>(EntityRollingStockDefinition.java:106) ~[EntityRollingStockDefinition.class:?]
	at cam72cam.immersiverailroading.registry.FreightDefinition.<init>(FreightDefinition.java:10) ~[FreightDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDefinition.<init>(LocomotiveDefinition.java:23) ~[LocomotiveDefinition.class:?]
	at cam72cam.immersiverailroading.registry.LocomotiveDieselDefinition.<init>(LocomotiveDieselDefinition.java:27) ~[LocomotiveDieselDefinition.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.lambda$static$0(DefinitionManager.java:46) ~[DefinitionManager.class:?]
	at cam72cam.immersiverailroading.registry.DefinitionManager.initDefinitions(DefinitionManager.java:147) [DefinitionManager.class:?]
	at cam72cam.immersiverailroading.proxy.CommonProxy.preInit(CommonProxy.java:113) [CommonProxy.class:?]
	at cam72cam.immersiverailroading.proxy.ServerProxy.preInit(ServerProxy.java:41) [ServerProxy.class:?]
	at cam72cam.immersiverailroading.ImmersiveRailroading.preInit(ImmersiveRailroading.java:45) [ImmersiveRailroading.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]```

**Comment by Larky2k** [comment]
Remove UnU IV pack from your mods list

**Comment by Larky2k** [comment]
Also that's not IR issue that's a poorly made RP that's causing your errors as they are not default stock.

**Comment by djdanby** [comment]
> 
> 
> Remove UnU IV pack from your mods list

Ok Thank you for Info :) I hope that helps :)
